name: RequestPR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
     ORG: ${${{ github.event.organization.location }} | cut -c29}
    steps:
      - run: echo ${{ github.event.workspace }}
      - run: echo ${{ github.event.organization.org }}
      - run: echo ${{ github.event.organization.url }}
      - run: echo $ORG
      - run: echo ${{ github.event.organization.location }}
      - run: echo ${{ github.event.repository.name }}


