name: RequestPR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.organisation.name }}
      - run: echo ${{ github.event.organization.name }}
      - run: echo ${{ github.event.organization }}
      - run: echo ${{ github.event.repository.name }}


