name: RequestPR
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.workspace }}
      - run: echo ${{ github.event.organization.org }}
      - run: echo ${{ github.event.organization.url }}
      - run: echo ${{ github.event.organization.location }}
      - run: echo ${{ github.event.repository.name }}


